[GLOBAL]
pants_version = "2.23.1"

backend_packages = [
  "pants.backend.build_files.fix.deprecations",
  "pants.backend.build_files.fmt.black",
  "pants.backend.experimental.python",
  "pants.backend.python",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pyupgrade",
  # "pants.backend.python.providers.experimental.pyenv",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.tools.preamble",
]

[shfmt]
args = "-i 4"

[python]
interpreter_constraints = ["==3.12.*"]
enable_resolves = true

[python.resolves]
python-default = "3rdparty/python/default.lock"

[setup-py-generation]
generate_setup_default = false

[docformatter]
args = ["--wrap-summaries=100", "--wrap-descriptions=100"]

[black]
install_from_resolve = "python-default"

[pytest]
install_from_resolve = "python-default"

[preamble]
template_by_globs = "@.preamble.yaml"

[twine]
install_from_resolve = "python-default"
